application: imperial-message-service
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.png
  static_files: static/favicon.png
  upload: static/favicon\.png

- url: /static
  static_dir: static

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: .*
  script: main.app

libraries:
- name: jinja2
  version: "2.6"

inbound_services:
- warmup
